### PR TITLE
Get rid of `createComponent`

### LINKED ISSUE #25: Question: what is the purpose of `createComponent`?
Hi Ciaran,

I'm wondering, what is the purpose of `createComponent` function?
It seems to be over-complicated, particularly `InputComponent` class component with `getRenderedComponent` method (which isn't used anyway).

### PR DESCRIPTION
**Pull request by cherniavskii**
Closes #25 

This is my first usage of TypeScript :D

I've had hard times defining Props interfaces for `Checkbox` and `Switch` - there's an error which says it's impossible to extend both FieldProps and MuiCheckboxProps, so I ended up with defining `React.ComponentType<FieldProps & MuiCheckboxProps>` for those components.
Surprisingly it worked.

### CODE REVIEW

**Comment by cliedeman** [comment]
there's an error which says it's impossible to extend both FieldProps and MuiCheckboxProps

Do you have the rest of the error? What it might be is that we have overlapping props and should remove one of them. Or at-least make it explicit which one we want to accept.

**Comment by cliedeman** [comment]
Its a bit hard to trace but:

CheckboxProps > SwitchBaseProps > IconButtonProps > ButtonBaseProps > [React.ButtonHTMLAttributes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1377)

And form is a valid [attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Attributes).

We can use omit to explicity state which key we are ignoring and this will probably be useful in other cases when we have key collisions.

```
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

interface Props extends FieldProps, Omit<MuiCheckboxProps, 'form'> {}
```

Can you please create a types.ts with `export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;` and then use that instead?

**Comment by cherniavskii** [comment]
> CheckboxProps > SwitchBaseProps > IconButtonProps > ButtonBaseProps > React.ButtonHTMLAttributes

image

:D

Sure, I'll update the PR later

**Comment by cliedeman** [comment]
Thanks for this! I accidentally merged while prettier was still failing.. doh. Anyway pushed another commit to fix the build.

Released 0.0.9

**Pull request merged**
